name: Latest blog post workflow
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update README with latest blog posts
        uses: gautamkrishnar/blog-post-workflow@v2
        with:
          maxPostCount: "4"
          feedList: "https://medium.com/feed/@nijithneo"
